//Database connection
const connectDB = require("../db/connect"); 


/**
 * Service to register a user to the database
 * Creates user record and assigns role in UserRoles junction table
 * Note record will have dateCreated, that is auto generated by the datahbase when created 
 * @param {*} firstName
 * @param {*} lastName
 * @param {*} idNumber
 * @param {*} emailAddress
 * @param {*} userPassword
 * @param {*} contactNo
 * @param {*} gender
 * @param {*} isActive
 * @returns The id of the user that has just been created/Registered
 */
const registerUser = async (
  firstName,
  lastName,
  idNumber,
  emailAddress,
  userPassword,
  contactNo,
  gender,
  userRole,
  isActive,
  title
) => {
  let connection;
  try {
    // Get a connection to use transaction
    connection = await connectDB.getConnection();
    await connection.beginTransaction();

    // Insert into Users table (without userRole)
    const [userResult] = await connection.execute(
      `
      INSERT INTO Users
      (firstName, lastName, idNumber, emailAddress, userPassword, contactNo, gender, isActive, title)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      `,
      [
        firstName,
        lastName,
        idNumber,
        emailAddress,
        userPassword,
        contactNo,
        gender,
        isActive,
        title
      ]
    );

    const userId = userResult.insertId;

    // Insert into UserRoles junction table
    await connection.execute(
      `
      INSERT INTO UserRoles
      (userId, userRole)
      VALUES (?, ?)
      `,
      [userId, userRole]
    );

    // Commit the transaction
    await connection.commit();

    return userId;
    
  } catch (error) {
    // Rollback on error
    if (connection) {
      await connection.rollback();
    }
    console.error("Failed to create user:", error);
    throw error;
  } finally {
    // Release the connection back to the pool
    if (connection) {
      connection.release();
    }
  }
};

const findUserByIdentifier = async (identifierNumber) => {
    try {
      // Try to find as student first
      const [students] = await connectDB.query(
        `SELECT u.* 
         FROM Users u 
         INNER JOIN Student s ON u.userId = s.studentId 
         WHERE s.studentNumber = ? AND u.isActive = TRUE`,
        [identifierNumber] // Where the identifierNumber represents the studentNumber
      );
      
      if (students.length > 0) {
        return students[0];
      }
      
      // If not student, try as staff (Lecturer, Coordinator, or HOD)
      const [staff] = await connectDB.query(
        `SELECT u.* 
         FROM Users u 
         WHERE u.userId IN (
           SELECT lecturerId FROM Lecturer WHERE staffNumber = ?
           UNION
           SELECT coordinatorId FROM Coordinator WHERE staffNumber = ?
           UNION
           SELECT hodId FROM HOD WHERE staffNumber = ?
         ) AND u.isActive = TRUE
         LIMIT 1`,
        [identifierNumber, identifierNumber, identifierNumber]
      );
      
      return staff.length > 0 ? staff[0] : null; //If there is something to return, return the first, if not return null
      
    } catch (error) {
      console.error('Error finding user:', error);
      throw error;
    }
  }

const getUserRoles = async (userId) => {
    try {
      const [roles] = await connectDB.query(
        'SELECT userRole FROM UserRoles WHERE userId = ?',
        [userId]
      );
      
      return roles.map(r => r.userRole);
      
    } catch (error) {
      console.error('Error getting user roles:', error);
      throw error;
    }
  }


/**
 * Automatically assigns modules to a student based on their qualification, year, and semester
 * Queries QualificationModule to find which modules should be assigned
 * @param {number} studentId - The student's user ID
 * @param {number} qualificationId - The qualification ID
 * @param {number} yearOfStudy - The academic year (1, 2, 3, etc.)
 * @param {number} semesterNo - The semester number (1 or 2)
 * @returns {Promise<Array>} Array of assigned modules
 */
const assignModulesToStudent = async (studentId, qualificationId, yearOfStudy, semesterNo) => {
  const connection = await connectDB.getConnection();
  
  try {
    await connection.beginTransaction();
    
    // Get all modules for this qualification, year, and semester
    const [modules] = await connection.query(
      `SELECT qm.moduleId, m.moduleName, m.moduleCode, m.credits, qm.isCompulsory
       FROM QualificationModule qm
       INNER JOIN Module m ON qm.moduleId = m.moduleId
       WHERE qm.qualificationId = ? 
       AND qm.academicYear = ? 
       AND qm.semesterNo = ?`,
      [qualificationId, yearOfStudy, semesterNo]
    );
    
    if (modules.length === 0) {
      await connection.commit();
      return [];
    }
    
    const assignedModules = [];
    
    // Insert each module into StudentModule
    for (const module of modules) {
      // Check if already assigned (prevent duplicates)
      const [existing] = await connection.query(
        'SELECT studentModuleId FROM StudentModule WHERE studentId = ? AND moduleId = ?',
        [studentId, module.moduleId]
      );
      
      if (existing.length === 0) {
        await connection.query(
          'INSERT INTO StudentModule (studentId, moduleId) VALUES (?, ?)',
          [studentId, module.moduleId]
        );
        
        assignedModules.push({
          moduleId: module.moduleId,
          moduleName: module.moduleName,
          moduleCode: module.moduleCode,
          credits: module.credits,
          isCompulsory: module.isCompulsory
        });
      }
    }
    
    await connection.commit();
    return assignedModules;
    
  } catch (error) {
    await connection.rollback();
    throw new Error(`Failed to assign modules to student: ${error.message}`);
  } finally {
    connection.release();
  }
};


/**
 * Assigns specific modules to a lecturer
 * @param {number} lecturerId - The lecturer's user ID
 * @param {Array<number>} moduleIds - Array of module IDs to assign
 * @returns {Promise<Array>} Array of assigned modules
 */
const assignModulesToLecturer = async (lecturerId, moduleIds) => {
  const connection = await connectDB.getConnection();
  
  try {
    await connection.beginTransaction();
    
    const assignedModules = [];
    
    for (const moduleId of moduleIds) {
      // Check if already assigned
      const [existing] = await connection.query(
        'SELECT lecturerModuleId FROM LecturerModule WHERE lecturerId = ? AND moduleId = ?',
        [lecturerId, moduleId]
      );
      
      if (existing.length === 0) {
        await connection.query(
          'INSERT INTO LecturerModule (lecturerId, moduleId) VALUES (?, ?)',
          [lecturerId, moduleId]
        );
        
        // Get module details
        const [moduleDetails] = await connection.query(
          'SELECT moduleId, moduleName, moduleCode, credits FROM Module WHERE moduleId = ?',
          [moduleId]
        );
        
        if (moduleDetails.length > 0) {
          assignedModules.push(moduleDetails[0]);
        }
      }
    }
    
    await connection.commit();
    return assignedModules;
    
  } catch (error) {
    await connection.rollback();
    throw new Error(`Failed to assign modules to lecturer: ${error.message}`);
  } finally {
    connection.release();
  }
};


/**
 * Assigns specific modules to a coordinator
 * @param {number} coordinatorId - The coordinator's user ID
 * @param {Array<number>} moduleIds - Array of module IDs to assign
 * @returns {Promise<Array>} Array of assigned modules
 */
const assignModulesToCoordinator = async (coordinatorId, moduleIds) => {
  const connection = await connectDB.getConnection();
  
  try {
    await connection.beginTransaction();
    
    const assignedModules = [];
    
    for (const moduleId of moduleIds) {
      // Check if already assigned
      const [existing] = await connection.query(
        'SELECT coordinatorModuleId FROM CoordinatorModule WHERE coordinatorId = ? AND moduleId = ?',
        [coordinatorId, moduleId]
      );
      
      if (existing.length === 0) {
        await connection.query(
          'INSERT INTO CoordinatorModule (coordinatorId, moduleId) VALUES (?, ?)',
          [coordinatorId, moduleId]
        );
        
        // Get module details
        const [moduleDetails] = await connection.query(
          'SELECT moduleId, moduleName, moduleCode, credits FROM Module WHERE moduleId = ?',
          [moduleId]
        );
        
        if (moduleDetails.length > 0) {
          assignedModules.push(moduleDetails[0]);
        }
      }
    }
    
    await connection.commit();
    return assignedModules;
    
  } catch (error) {
    await connection.rollback();
    throw new Error(`Failed to assign modules to coordinator: ${error.message}`);
  } finally {
    connection.release();
  }
};

const loginUser = async (identifierNumber) => {
  try {
      // Find user by studentNumber or staffNumber
      // At this point, even if we get the user, we still do not know their role, it is located in the UserRoles junction table,
      // because, a user can have multiple roles
      const user = await findUserByIdentifier(identifierNumber);

      if (!user) {
        return { code: "Unsuccessful", msg: 'Invalid student/staff number or password'};
      }

      // Get the user's role(s), using the id retrieved from the user we identfied 
      const roles = await getUserRoles(user.userId);

      // return only the information, I see as necessary for now 
      return {
        user: {
          userId: user.userId,
          firstName: user.firstName,
          lastName: user.lastName,
          userPassword: user.userPassword, // I always prefer to do the bcrypt validation on the controller
          title: user.title,
          emailAddress: user.emailAddress,
          contactNo: user.contactNo,
          gender: user.gender,
          roles: roles, // Will need this immediately after the login
        }
      };

  } catch (error) {
      console.error('Error login in user:', error);
      throw error;
  }
}

/**
 * DEV ONLY - the pain of writing this ;;;;;
 * Updates a user's password using studentNumber or staffNumber
 * @param {*} identifierNumber
 * @param {*} hashedPassword
 * @returns true if updated, false otherwise
 */
const updatePasswordByIdentifier = async (identifierNumber, hashedPassword) => {
  let connection;

  try {
    connection = await connectDB.getConnection();
    await connection.beginTransaction();

    // Find userId first (same logic as login)
    const user = await findUserByIdentifier(identifierNumber);

    if (!user) {
      await connection.rollback();
      return false;
    }

    // Update password
    const [result] = await connection.execute(
      `
      UPDATE Users
      SET userPassword = ?
      WHERE userId = ?
      `,
      [hashedPassword, user.userId]
    );

    await connection.commit();

    return result.affectedRows > 0;

  } catch (error) {
    if (connection) await connection.rollback();
    console.error("Failed to update password:", error);
    throw error;
  } finally {
    if (connection) connection.release();
  }
};

module.exports = {
  registerUser,
  loginUser,
  updatePasswordByIdentifier,
  assignModulesToStudent,
  assignModulesToLecturer,
  assignModulesToCoordinator,
};