//Database connection
const connectDB = require("../db/connect"); 


/**
 * Service to register a user to the database
 * Creates user record and assigns role in UserRoles junction table
 * Note record will have dateCreated, that is auto generated by the datahbase when created 
 * @param {*} firstName
 * @param {*} lastName
 * @param {*} idNumber
 * @param {*} emailAddress
 * @param {*} userPassword
 * @param {*} contactNo
 * @param {*} gender
 * @param {*} isActive
 * @returns The id of the user that has just been created/Registered
 */
const registerUser = async (
  firstName,
  lastName,
  idNumber,
  emailAddress,
  userPassword,
  contactNo,
  gender,
  userRole,
  isActive,
  title
) => {
  let connection;
  try {
    // Get a connection to use transaction
    connection = await connectDB.getConnection();
    await connection.beginTransaction();

    // Insert into Users table (without userRole)
    const [userResult] = await connection.execute(
      `
      INSERT INTO Users
      (firstName, lastName, idNumber, emailAddress, userPassword, contactNo, gender, isActive, title)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      `,
      [
        firstName,
        lastName,
        idNumber,
        emailAddress,
        userPassword,
        contactNo,
        gender,
        isActive,
        title
      ]
    );

    const userId = userResult.insertId;

    // Insert into UserRoles junction table
    await connection.execute(
      `
      INSERT INTO UserRoles
      (userId, userRole)
      VALUES (?, ?)
      `,
      [userId, userRole]
    );

    // Commit the transaction
    await connection.commit();

    return userId;
    
  } catch (error) {
    // Rollback on error
    if (connection) {
      await connection.rollback();
    }
    console.error("Failed to create user:", error);
    throw error;
  } finally {
    // Release the connection back to the pool
    if (connection) {
      connection.release();
    }
  }
};

const findUserByIdentifier = async (identifierNumber) => {
    try {
      // Try to find as student first
      const [students] = await connectDB.query(
        `SELECT u.* 
         FROM Users u 
         INNER JOIN Student s ON u.userId = s.studentId 
         WHERE s.studentNumber = ? AND u.isActive = TRUE`,
        [identifierNumber] // Where the identifierNumber represents the studentNumber
      );
      
      if (students.length > 0) {
        return students[0];
      }
      
      // If not student, try as staff (Lecturer, Coordinator, or HOD)
      const [staff] = await connectDB.query(
        `SELECT u.* 
         FROM Users u 
         WHERE u.userId IN (
           SELECT lecturerId FROM Lecturer WHERE staffNumber = ?
           UNION
           SELECT coordinatorId FROM Coordinator WHERE staffNumber = ?
           UNION
           SELECT hodId FROM HOD WHERE staffNumber = ?
         ) AND u.isActive = TRUE
         LIMIT 1`,
        [identifierNumber, identifierNumber, identifierNumber]
      );
      
      return staff.length > 0 ? staff[0] : null; //If there is something to return, return the first, if not return null
      
    } catch (error) {
      console.error('Error finding user:', error);
      throw error;
    }
  }

const getUserRoles = async (userId) => {
    try {
      const [roles] = await connectDB.query(
        'SELECT userRole FROM UserRoles WHERE userId = ?',
        [userId]
      );
      
      return roles.map(r => r.userRole);
      
    } catch (error) {
      console.error('Error getting user roles:', error);
      throw error;
    }
  }

const loginUser = async (identifierNumber) => {
  try {
      // Find user by studentNumber or staffNumber
      // At this point, even if we get the user, we still do not know their role, it is located in the UserRoles junction table,
      // because, a user can have multiple roles
      const user = await findUserByIdentifier(identifierNumber);

      if (!user) {
        return { code: "Unsuccessful", msg: 'Invalid student/staff number or password'};
      }

      // Get the user's role(s), using the id retrieved from the user we identfied 
      const roles = await getUserRoles(user.userId);

      // return only the information, I see as necessary for now 
      return {
        user: {
          userId: user.userId,
          firstName: user.firstName,
          lastName: user.lastName,
          userPassword: user.userPassword, // I always prefer to do the bcrypt validation on the controller
          title: user.title,
          emailAddress: user.emailAddress,
          contactNo: user.contactNo,
          gender: user.gender,
          roles: roles, // Will need this immediately after the login
        }
      };

  } catch (error) {
      console.error('Error login in user:', error);
      throw error;
  }
}

module.exports = {
  registerUser,
  loginUser
};